In [4]:
from os import listdir
from os.path import isfile, join
import numpy as np
import cv2
import random

In [5]:
#Loading images into arrays
mypath = '/Users/jasleenkaur/Desktop/Masters/Spring 2022/Image Analysis/Project/Cancerous cell smears/'
cellFiles = [f for f in listdir(mypath) if isfile(join(mypath,f))]
originalImages = np.empty(len(cellFiles),dtype=object)
grayscaleImages = np.empty(len(cellFiles),dtype=object)
for n in range(0,len(cellFiles)):
    originalImages[n] = cv2.imread(join(mypath,cellFiles[n]))
    grayscaleImages[n] = cv2.imread(join(mypath,cellFiles[n]), 0)
    

print(len(cellFiles))
#originalImages[1].size, originalImages[1].shape, originalImages[1].ndim
#grayscaleImages[1].size, grayscaleImages[1].shape, grayscaleImages[1].ndim
#cv2.imshow('Sample image', images[1])
#cv2.waitKey(0)
#cv2.destroyAllWindows()


500


In [10]:
#Salt and Pepper noise

#copy the array of immages to modify
saltPepperArray = grayscaleImages
#print(len(saltPepperArray))
#print(len(originalImages))


def saltPepper(saltPepperArray):
    number_of_pixels = random.randint(300,10000)
    row, col = saltPepperArray.shape
    for eachImage in saltPepperArray:
        row, col = saltPepperArray[eachImage]
    for n in saltPepperArray:
        for i in range(number_of_pixels):
            y_coord=random.randint(0,row-1)
            x_coord=random.randint(0,col-1)
            n[y_coord][x_coord] = 255
    
        number_of_pixels = random.randint(300,10000)
        for i in range(number_of_pixels):
            y_coord=random.randint(0,row-1)
            x_coord=random.randint(0,col-1)
            n[y_coord][x_coord] = 0
    return saltPepperArray


cv2.imwrite(cellFiles, saltPepper(saltPepperArray))
cv2.imshow('SaltPepper Image', saltPepperArray[1])
cv2.waitKey(0)
cv2.destroyAllWindows()



ValueError: not enough values to unpack (expected 2, got 1)

In [ ]:
cv2.imshow('Grayscale image', grayscaleImages[1])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
print(grayscaleImages[1])

[[  2  36 107 ... 155 156 159]
 [  5  27  93 ... 159 157 155]
 [  5  33  99 ... 156 156 158]
 ...
 [ 16  85 162 ... 188 186 188]
 [ 10  58 107 ... 143 143 143]
 [  6  19  22 ...  26  28  23]]


In [11]:
print(originalImages[1])

[[[ 11   1   1]
  [ 45  35  33]
  [119 105 107]
  ...
  [157 155 153]
  [157 157 153]
  [161 159 157]]

 [[  1   1  13]
  [ 17  23  37]
  [ 85  89 105]
  ...
  [155 159 161]
  [153 157 159]
  [151 155 157]]

 [[  1   1  13]
  [ 17  31  43]
  [ 83  97 109]
  ...
  [155 155 159]
  [157 155 159]
  [157 157 159]]

 ...

 [[  1  13  27]
  [ 47  85  99]
  [121 163 175]
  ...
  [141 195 193]
  [141 193 191]
  [145 193 193]]

 [[  5   7  19]
  [ 53  55  65]
  [105 103 115]
  ...
  [129 143 149]
  [129 143 149]
  [137 141 149]]

 [[  1   5   9]
  [  1  21  23]
  [  1  25  23]
  ...
  [  1  33  23]
  [  1  33  27]
  [  1  27  25]]]


In [6]:
originalImages[1].size, originalImages[1].shape, originalImages[1].ndim

(1308672, (568, 768, 3), 3)

In [7]:
grayscaleImages[1].size, grayscaleImages[1].shape, grayscaleImages[1].ndim

(436224, (568, 768), 2)

In [6]:
grayscaleImages[1].shape

(568, 768)

In [ ]:
#saltPepper on One Image
import cv2
import random

def saltPepperNoise(image):
    row, col = image.shape
    num_pixls = 100 #user input value
    for i in range(num_pixls):
        y_crd = random.randint(0,row-1)
        x_crd = random.randint(0,col-1)
        image[y_crd][x_crd]=255
    for i in range(num_pixls):
        y_crd = random.randint(0,row-1)
        x_crd = random.randint(0,col-1)
        image[y_crd][x_crd]=0
    return image

image = cv2.imread("/Users/jasleenkaur/Desktop/Masters/Spring 2022/Image Analysis/Project/Cancerous cell smears/cyl01.bmp", 0)
cv2.imwrite("/Users/jasleenkaur/Desktop/Masters/Spring 2022/Image Analysis/Project/Salt&Pepper/cyl01.bmp", saltPepperNoise(image))
cv2.imshow('image-noise',image)
cv2.waitKey(0)
cv2.destroyAllWindows()
                  

In [3]:
import cv2
image = cv2.imread("/Users/jasleenkaur/Desktop/Masters/Spring 2022/Image Analysis/Project/Cancerous cell smears/cyl01.bmp", 0)
image.shape


(568, 768)

In [ ]:
image.shape