In [19]:
#prewitt and sobel on one image

import cv2
import numpy as np


def prewittAndSobel (image, horizontal, vertical):
    
    # Apply gray scale
    gray_img = np.round(0.2989 * img[:, :, 0] +
                        0.5870 * img[:, :, 1] +
                        0.1140 * img[:, :, 2]).astype(np.uint8)

    height, width = gray_img.shape

    newgradientImage = np.zeros((h, w))

    for i in range(1, height - 1):
        for j in range(1, width - 1):
            horizontalGrad = (horizontal[0, 0] * gray_img[i - 1, j - 1]) + \
                             (horizontal[0, 1] * gray_img[i - 1, j]) + \
                             (horizontal[0, 2] * gray_img[i - 1, j + 1]) + \
                             (horizontal[1, 0] * gray_img[i, j - 1]) + \
                             (horizontal[1, 1] * gray_img[i, j]) + \
                             (horizontal[1, 2] * gray_img[i, j + 1]) + \
                             (horizontal[2, 0] * gray_img[i + 1, j - 1]) + \
                             (horizontal[2, 1] * gray_img[i + 1, j]) + \
                             (horizontal[2, 2] * gray_img[i + 1, j + 1])

            verticalGrad = (vertical[0, 0] * gray_img[i - 1, j - 1]) + \
                           (vertical[0, 1] * gray_img[i - 1, j]) + \
                           (vertical[0, 2] * gray_img[i - 1, j + 1]) + \
                           (vertical[1, 0] * gray_img[i, j - 1]) + \
                           (vertical[1, 1] * gray_img[i, j]) + \
                           (vertical[1, 2] * gray_img[i, j + 1]) + \
                           (vertical[2, 0] * gray_img[i + 1, j - 1]) + \
                           (vertical[2, 1] * gray_img[i + 1, j]) + \
                           (vertical[2, 2] * gray_img[i + 1, j + 1])

            # Edge Magnitude
            mag = np.sqrt(pow(horizontalGrad, 2.0) + pow(verticalGrad, 2.0))
            newgradientImage[i - 1, j - 1] = mag
    
    return newgradientImage

image = cv2.imread("/Users/jasleenkaur/Desktop/Masters/Spring 2022/Image Analysis/Project/Cancerous cell smears/cyl01.bmp")

prewittHorizontal = np.array([[-1, 0, 1], [-1, 0, 1], [-1, 0, 1]])
prewittVertical = np.array([[-1, -1, -1], [0, 0, 0], [1, 1, 1]])

sobelHorizontal = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]]) 
sobelVertical = np.array([[-1, -2, -1], [0, 0, 0], [1, 2, 1]])

newImage = prewittAndSobel(image, prewittHorizontal, prewittVertical)
cv2.imwrite("/Users/jasleenkaur/Desktop/Masters/Spring 2022/Image Analysis/Project/Sobel/Prewittcyl01.bmp", newImage)

newImage = prewittAndSobel(image, sobelHorizontal, sobelVertical)
cv2.imwrite("/Users/jasleenkaur/Desktop/Masters/Spring 2022/Image Analysis/Project/Sobel/Sobelcyl01.bmp", newImage)



True

In [23]:
#Compass operator

import cv2
import numpy as np


def compassOperator (image, k1, k2, k3, k4):
    
    # Apply gray scale
    gray_img = np.round(0.2989 * img[:, :, 0] +
                        0.5870 * img[:, :, 1] +
                        0.1140 * img[:, :, 2]).astype(np.uint8)

    height, width = gray_img.shape

    newgradientImage = np.zeros((h, w))

    for i in range(1, height - 1):
        for j in range(1, width - 1):
            k1Grad = (k1[0, 0] * gray_img[i - 1, j - 1]) + \
                     (k1[0, 1] * gray_img[i - 1, j]) + \
                     (k1[0, 2] * gray_img[i - 1, j + 1]) + \
                     (k1[1, 0] * gray_img[i, j - 1]) + \
                     (k1[1, 1] * gray_img[i, j]) + \
                     (k1[1, 2] * gray_img[i, j + 1]) + \
                     (k1[2, 0] * gray_img[i + 1, j - 1]) + \
                     (k1[2, 1] * gray_img[i + 1, j]) + \
                     (k1[2, 2] * gray_img[i + 1, j + 1])

            k2Grad = (k2[0, 0] * gray_img[i - 1, j - 1]) + \
                     (k2[0, 1] * gray_img[i - 1, j]) + \
                     (k2[0, 2] * gray_img[i - 1, j + 1]) + \
                     (k2[1, 0] * gray_img[i, j - 1]) + \
                     (k2[1, 1] * gray_img[i, j]) + \
                     (k2[1, 2] * gray_img[i, j + 1]) + \
                     (k2[2, 0] * gray_img[i + 1, j - 1]) + \
                     (k2[2, 1] * gray_img[i + 1, j]) + \
                     (k2[2, 2] * gray_img[i + 1, j + 1])
            
            k3Grad = (k3[0, 0] * gray_img[i - 1, j - 1]) + \
                     (k3[0, 1] * gray_img[i - 1, j]) + \
                     (k3[0, 2] * gray_img[i - 1, j + 1]) + \
                     (k3[1, 0] * gray_img[i, j - 1]) + \
                     (k3[1, 1] * gray_img[i, j]) + \
                     (k3[1, 2] * gray_img[i, j + 1]) + \
                     (k3[2, 0] * gray_img[i + 1, j - 1]) + \
                     (k3[2, 1] * gray_img[i + 1, j]) + \
                     (k3[2, 2] * gray_img[i + 1, j + 1])
            
            k4Grad = (k4[0, 0] * gray_img[i - 1, j - 1]) + \
                     (k4[0, 1] * gray_img[i - 1, j]) + \
                     (k4[0, 2] * gray_img[i - 1, j + 1]) + \
                     (k4[1, 0] * gray_img[i, j - 1]) + \
                     (k4[1, 1] * gray_img[i, j]) + \
                     (k4[1, 2] * gray_img[i, j + 1]) + \
                     (k4[2, 0] * gray_img[i + 1, j - 1]) + \
                     (k4[2, 1] * gray_img[i + 1, j]) + \
                     (k4[2, 2] * gray_img[i + 1, j + 1])

            # Edge Magnitude
            mag = np.sqrt(pow(k1Grad, 2.0) + pow(k2Grad, 2.0) + pow(k3Grad, 2.0) + pow(k4Grad, 2.0))
            newgradientImage[i - 1, j - 1] = mag
    
    return newgradientImage

image = cv2.imread("/Users/jasleenkaur/Desktop/Masters/Spring 2022/Image Analysis/Project/Cancerous cell smears/cyl01.bmp")

k1 = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
k2 = np.array([[-2, -1, 0], [-1, 0, 1], [0, 1, 2]])
k3 = np.array([[-1, -2, -1], [0, 0, 0], [1, 2, 1]]) 
k4 = np.array([[0, -1, -2], [1, 0, -1], [2, 1, 0]])

newImage = compassOperator(image, k1, k2, k3, k4)
cv2.imwrite("/Users/jasleenkaur/Desktop/Masters/Spring 2022/Image Analysis/Project/Sobel/Compasscyl01.bmp", newImage)



True

In [29]:
#Compass operator with 8

import cv2
import numpy as np


def compassOperator (image, k1, k2, k3, k4, k5, k6, k7, k8):
    
    # Apply gray scale
    gray_img = np.round(0.2989 * img[:, :, 0] +
                        0.5870 * img[:, :, 1] +
                        0.1140 * img[:, :, 2]).astype(np.uint8)

    height, width = gray_img.shape

    newgradientImage = np.zeros((h, w))

    for i in range(1, height - 1):
        for j in range(1, width - 1):
            k1Grad = (k1[0, 0] * gray_img[i - 1, j - 1]) + \
                     (k1[0, 1] * gray_img[i - 1, j]) + \
                     (k1[0, 2] * gray_img[i - 1, j + 1]) + \
                     (k1[1, 0] * gray_img[i, j - 1]) + \
                     (k1[1, 1] * gray_img[i, j]) + \
                     (k1[1, 2] * gray_img[i, j + 1]) + \
                     (k1[2, 0] * gray_img[i + 1, j - 1]) + \
                     (k1[2, 1] * gray_img[i + 1, j]) + \
                     (k1[2, 2] * gray_img[i + 1, j + 1])

            k2Grad = (k2[0, 0] * gray_img[i - 1, j - 1]) + \
                     (k2[0, 1] * gray_img[i - 1, j]) + \
                     (k2[0, 2] * gray_img[i - 1, j + 1]) + \
                     (k2[1, 0] * gray_img[i, j - 1]) + \
                     (k2[1, 1] * gray_img[i, j]) + \
                     (k2[1, 2] * gray_img[i, j + 1]) + \
                     (k2[2, 0] * gray_img[i + 1, j - 1]) + \
                     (k2[2, 1] * gray_img[i + 1, j]) + \
                     (k2[2, 2] * gray_img[i + 1, j + 1])
            
            k3Grad = (k3[0, 0] * gray_img[i - 1, j - 1]) + \
                     (k3[0, 1] * gray_img[i - 1, j]) + \
                     (k3[0, 2] * gray_img[i - 1, j + 1]) + \
                     (k3[1, 0] * gray_img[i, j - 1]) + \
                     (k3[1, 1] * gray_img[i, j]) + \
                     (k3[1, 2] * gray_img[i, j + 1]) + \
                     (k3[2, 0] * gray_img[i + 1, j - 1]) + \
                     (k3[2, 1] * gray_img[i + 1, j]) + \
                     (k3[2, 2] * gray_img[i + 1, j + 1])
            
            k4Grad = (k4[0, 0] * gray_img[i - 1, j - 1]) + \
                     (k4[0, 1] * gray_img[i - 1, j]) + \
                     (k4[0, 2] * gray_img[i - 1, j + 1]) + \
                     (k4[1, 0] * gray_img[i, j - 1]) + \
                     (k4[1, 1] * gray_img[i, j]) + \
                     (k4[1, 2] * gray_img[i, j + 1]) + \
                     (k4[2, 0] * gray_img[i + 1, j - 1]) + \
                     (k4[2, 1] * gray_img[i + 1, j]) + \
                     (k4[2, 2] * gray_img[i + 1, j + 1])
            
            k5Grad = (k5[0, 0] * gray_img[i - 1, j - 1]) + \
                     (k5[0, 1] * gray_img[i - 1, j]) + \
                     (k5[0, 2] * gray_img[i - 1, j + 1]) + \
                     (k5[1, 0] * gray_img[i, j - 1]) + \
                     (k5[1, 1] * gray_img[i, j]) + \
                     (k5[1, 2] * gray_img[i, j + 1]) + \
                     (k5[2, 0] * gray_img[i + 1, j - 1]) + \
                     (k5[2, 1] * gray_img[i + 1, j]) + \
                     (k5[2, 2] * gray_img[i + 1, j + 1])
            
            k6Grad = (k6[0, 0] * gray_img[i - 1, j - 1]) + \
                     (k6[0, 1] * gray_img[i - 1, j]) + \
                     (k6[0, 2] * gray_img[i - 1, j + 1]) + \
                     (k6[1, 0] * gray_img[i, j - 1]) + \
                     (k6[1, 1] * gray_img[i, j]) + \
                     (k6[1, 2] * gray_img[i, j + 1]) + \
                     (k6[2, 0] * gray_img[i + 1, j - 1]) + \
                     (k6[2, 1] * gray_img[i + 1, j]) + \
                     (k6[2, 2] * gray_img[i + 1, j + 1])
            
            k7Grad = (k7[0, 0] * gray_img[i - 1, j - 1]) + \
                     (k7[0, 1] * gray_img[i - 1, j]) + \
                     (k7[0, 2] * gray_img[i - 1, j + 1]) + \
                     (k7[1, 0] * gray_img[i, j - 1]) + \
                     (k7[1, 1] * gray_img[i, j]) + \
                     (k7[1, 2] * gray_img[i, j + 1]) + \
                     (k7[2, 0] * gray_img[i + 1, j - 1]) + \
                     (k7[2, 1] * gray_img[i + 1, j]) + \
                     (k7[2, 2] * gray_img[i + 1, j + 1])
            
            k8Grad = (k8[0, 0] * gray_img[i - 1, j - 1]) + \
                     (k8[0, 1] * gray_img[i - 1, j]) + \
                     (k8[0, 2] * gray_img[i - 1, j + 1]) + \
                     (k8[1, 0] * gray_img[i, j - 1]) + \
                     (k8[1, 1] * gray_img[i, j]) + \
                     (k8[1, 2] * gray_img[i, j + 1]) + \
                     (k8[2, 0] * gray_img[i + 1, j - 1]) + \
                     (k8[2, 1] * gray_img[i + 1, j]) + \
                     (k8[2, 2] * gray_img[i + 1, j + 1])

            # Edge Magnitude
            mag = np.sqrt(pow(k1Grad, 2.0) + pow(k2Grad, 2.0) + pow(k3Grad, 2.0) + pow(k4Grad, 2.0) + pow(k5Grad, 2.0) + pow(k6Grad, 2.0) + pow(k7Grad, 2.0) + pow(k8Grad, 2.0))
            newgradientImage[i - 1, j - 1] = mag
    
    return newgradientImage

image = cv2.imread("/Users/jasleenkaur/Desktop/Masters/Spring 2022/Image Analysis/Project/Cancerous cell smears/cyl01.bmp")

k1 = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
k2 = np.array([[-2, -1, 0], [-1, 0, 1], [0, 1, 2]])
k3 = np.array([[-1, -2, -1], [0, 0, 0], [1, 2, 1]]) 
k4 = np.array([[0, -1, -2], [1, 0, -1], [2, 1, 0]])

#k5 = np.array([[1, 0, -1], [2, 0, -2], [1, 0, -1]])
#k6 = np.array([[2, 1, 0], [1, 0, -1], [0, -1, -2]])
#k7 = np.array([[1, 2, 1], [0, 0, 0], [-1, -2, -1]]) 
#k8 = np.array([[0, 1, 2], [-1, 0, 1], [-2, -1, 0]])


newImage = compassOperator(image, k1, k2, k3, k4, -k1, -k2, -k3, -k4)
cv2.imwrite("/Users/jasleenkaur/Desktop/Masters/Spring 2022/Image Analysis/Project/Sobel/Compass8cyl01.bmp", newImage)



True

In [28]:
k1 = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
k2 = np.array(-k1)
print(k1)
print(k2)

[[-1  0  1]
 [-2  0  2]
 [-1  0  1]]
[[ 1  0 -1]
 [ 2  0 -2]
 [ 1  0 -1]]
